### ISSUE TITLE
Poll API for updated analysis status

### ISSUE THREAD

**Issue by adelavega** [neuroscout/neuroscout#115]
Doesn't look like the analysis status is being updated correctly. Only when I click "edit" from the homepage will the analysis update I believe.

It should probably check every x seconds, or everytime a tab changed if the status is "PENDING"

**Comment by skept** [comment]
Yeah, it currently doesn't poll the server to see if the analysis is still "Pending". It's a good idea though. Should we be doing this on both the Analysis Builder page and homepage (which would normally have a list of analyses)? How long does it typically take for the analysis run to complete?

**Comment by adelavega** [comment]
I'm still working on compiling... and that may vary. For now it's simple so maybe a minute but in the future we may do heavier validation. Everytime you do an API call to analysis, I update that field, FYI, so need to check a special "status" route.

**Comment by skept** [comment]
Ok, related to this, have you also figured out what the server will return as the analysis results? Perhaps for now you can just return a JSON field that I'll just blindly display in the review or status tab? Once I know this I can implement polling and updating the status/results.

**Comment by adelavega** [comment]
No all we need is to tell the user it is compiled. It means they can now go run the actual analysis on their computer, so we will add those instructions later. at /api/analysis/{id}/bundle the full analysis can be fetched by the command line interface, so compiling makes that end point available, but I don't think you need to worry about it aside from alerting the user to the status for now.

**Comment by skept** [comment]
Ok, that makes more sense now. I thought the analysis would automatically run on the server. Do you already have a route for just querying the status? If not, I think at least for now it should be fine to just poll `/api/analyses/{analysis_id}`. The payload is pretty small and it happens in the background so a slightly faster route is unlikely to increase the perceived speed of the UI.

**Comment by adelavega** [comment]
Yeah that works for now. If we hit performance issues we can change approach.

**Comment by rwblair** [comment]
fixed in #283
