### ISSUE TITLE
Get new auth token when expired

### ISSUE THREAD

**Issue by adelavega** [neuroscout/neuroscout#146]
JWT tokens include their expiration date. The frontend should check this, and ask for a new token periodically.

One option, is to check when given an API error (e.g. signature is expired), rather than given a new time period. Alternatively, could check the signature and if its close to expiration, get a new one.

**Comment by adelavega** [comment]
@rwblair Let's check on this issue, as its rather important. At the minimum it would be good if the user was "logged out" and asked to just sign in again. That's probably reasonable as most websites force that upon you.

**Comment by rwblair** [comment]
fixed by #374
