### ISSUE TITLE
Search clears filtering predictors

### ISSUE THREAD

**Issue by adelavega** [neuroscout/neuroscout#173]
When predictors are filtered the previously selected predictors are cleared out.

**Comment by rwblair** [comment]
Was there a specific predictor selector you were seeing this on? I tested on the predictors, transformations, and contrasts tab and was not able to recreate. 

Selecting multiple predictors:
<img width="852" alt="screen shot 2018-05-25 at 10 38 30 am" src="https://user-images.githubusercontent.com/14927911/40558432-286808b0-6008-11e8-9e7b-9becf14809ef.png">

Type in search until it reduces available predictors:
<img width="815" alt="screen shot 2018-05-25 at 10 38 52 am" src="https://user-images.githubusercontent.com/14927911/40558437-2bf4f3d0-6008-11e8-94b4-6126e14d9d01.png">

Remove search until other predictor shows up:
<img width="820" alt="screen shot 2018-05-25 at 10 39 06 am" src="https://user-images.githubusercontent.com/14927911/40558442-2e5c781e-6008-11e8-91cd-060339aceb46.png">

**Comment by adelavega** [comment]
It's only when you select a new predictor from the shortened list that it gets cleared out

**Comment by adelavega** [comment]
The HRF_Variables also become out of sync in this situation. And sometimes the list to the right also becomes out of sync with its respective panel.
