### ISSUE TITLE
NeuroVault integration

### ISSUE THREAD

**Issue by adelavega** [neuroscout/neuroscout#196]
Neuroscout CLI should be able to push fitted images to NeuroVault seamlessly.

First, how to handle authentication? 
 - Ideally, if your account is the same email as NeuroVault (especially if you used single sign in with say Google) you shouldn't need to authenticate to push to NeuroVault. However, this probably requires an integration step to pre-authenticate users w/ NeuroVault. We could automatically do this for all matching email addresses automatically though. 
 - A less optimal solution is to ask for user name and password at the command line and cache authentication token once we get it from the NeuroVault API

Also, does NeuroVault API have push routes? How easy is it to push?
Ideally there should be a lightweight python library for NeuroVault API

For reference, see how Neurolearn integrates with NeuroVault, and talk to @chrisfilo

**Comment by chrisfilo** [comment]
I wonder if upload shouldn't be built directly into fitlins. What do you think @tyarkoni @effigies?

BTW neurolearn has a reference implementation of NeuroVault upload: http://neurolearn.readthedocs.io/en/latest/auto_examples/01_DataOperations/plot_neurovault_io.html#upload-data-to-neurovault

It might be worth abstracting this into pyneurovault.

**Comment by adelavega** [comment]
There is also pynv: https://github.com/neurolearn/pynv
Not sure if that covers the full range of functionality of neurovault.

Building it into fitlins is a good idea, IMO. But we could get a head start on it while the core functionality of fitlins falls into place.

**Comment by adelavega** [comment]
@chrisfilo I've looked over the SPM integration guideline and tested using pynv to push collections to NeuroVault. Looks very doable for a first pass. 

Now, I'm wondering if theres a way for NeuroScout to authorize users on NeuroVault without having to ask users to manually create an API key? Looks like Neuro-learn does this (although its currently broken). I also see "Connected " and "Developer" application tabs in the "Settings" that might have to do with this? Let me know if this is documented anywhere. Ideally, our users are auto-authorized if they use the same email as NeuroVault (through single sign on), or they can click on a "Authorize NeuroVault" button which then caches their API key for the CLI to use.

**Comment by chrisfilo** [comment]
The API was not designed to be an authentication server so I am not sure how would this work. Is this feature critical?

**Comment by adelavega** [comment]
No, it a nice-to-have. I'll do it with manual log in first, and we can come back around to this later.

If we can use the same mechanism neuro-learn uses that might be relatively easy, though.
