### ISSUE TITLE
Add new fields to variable selection table

### ISSUE THREAD

**Issue by adelavega** [neuroscout/neuroscout#285]
New columns: modality, tags, and description (which trails off with ... and tooltip lets you see full description)

**Comment by adelavega** [comment]
Tags should also have the classic 'tag' aesthetic and let you click to filter

**Comment by adelavega** [comment]
This requires the backend to expose these attributes, and the FeatureSchema to add tags.

**Comment by adelavega** [comment]
I think for now just nice descriptions + ExtractorName should be fine

**Comment by rwblair** [comment]
Had been some talk ago about merging the description and extractor columns, I forget if we decided for or against it. Currently in #307 they are seperate columns. Not sure how the two parts in a single column would be styled atm.

**Comment by adelavega** [comment]
I think we would want to stylize it in separate columns (`Extractor Name` and `description`)
