### ISSUE TITLE
Template for "run" tab

### ISSUE THREAD

**Issue by adelavega** [neuroscout/neuroscout#289]
Once an analysis is compiled, we should have a quick blurb on how to run this analysis. 

E.g.
To run this analysis, the the following command in your local terminal:
    neuroscout run xgfd

We can link to yet to be written documentation for further explanation.

**Comment by adelavega** [comment]
**If analysis "fails" report:**

Your analysis design is failing diagnostics.
`{Error shown here}`
Please edit your analysis to fix the error and use the "reports" tab to check the validity of your analysis.

**If analysis "passes" reports:**

To run, submit your analysis for a final validation, and to generate an downloadable bundle.

- I agree that once I submit my analysis, I will not be able to delete or edit it.
- I agree to use the "clone" feature to create any forked versions of the current analysis
- If private: I understand that although my analysis is currently _private_, anyone with the analysis ID may view this analysis, and subsequent uploaded results.
- If public: I understand that my analysis is currently _public_ and will be searchable by other users.

[ ] I have read and agree to Neuroscout's terms of service.

[Compile]


**Once submitted for compilation:**
`[Submitting/Pending]`

**If analysis fails:**
Oh no! It looks like your analysis failed to compile. Please edit your analysis and try again. If the issue remains, please file a bugreport (link)
`[Error report]`

**If analysis passes:**
Congratulations! Your analysis is finished compiling and is ready to be executed. 
Once you have installed `neuroscout-cli` you may run your analysis like this:

`docker run -it -v /local/outputdirectory:/out neuroscout-cli run /out 97kO9`

See the `neuroscout-cli` documentation (link) for more information on how to install and run analyses.

**Comment by rwblair** [comment]
fixed in #384
