### ISSUE TITLE
Feedback on predictor annotation names

### ISSUE THREAD

**Issue by adelavega** [neuroscout/neuroscout#309]
I've annotated most Extracted Features and Predictors. It would be great to get feedback on how useful the annotated descriptions are, and what other annotations would be useful to have.

**Comment by tyarkoni** [comment]
Looked at a bunch on alpha; they look great! I think for the ones like `landmark_LEFT_EYE_BOTTOM_BOUNDARY_x` it's not worth the effort to annotate, but maybe put a generic description like "landmark face feature (name hopefully self-explanatory)" for all of them.
