### ISSUE TITLE
Add modality to dataset description

### ISSUE THREAD

**Issue by adelavega** [neuroscout/neuroscout#318]
For quick glance

**Comment by adelavega** [comment]
@tyarkoni do you think it would be most useful to show all the modalities available, or the original modality. For example, for movies, the original modality is audio/visual, but derived modalities and video, audio, image, maybe even speech.

**Comment by tyarkoni** [comment]
If it's at the dataset level, probably just a short descriptor of the study stimuli/design. This doesn't even need to be a pliers modality; I'm thinking something like "movies", "audio narrative", "reading", etc.

**Comment by adelavega** [comment]
In that case, the hand crafted descriptions I've added for each dataset may cover it. We could later add "badges" for different types of stimuli.
