### ISSUE TITLE
Add "replace na" a transformation (final step)

### ISSUE THREAD

**Issue by adelavega** [neuroscout/neuroscout#329]
By default, NAs should be replaced by 0s after transformations. This should be a checkbox in the 'config' tab.

Or perhaps this should be a transformation, so that it is more explicit in the BIDS model.

**Comment by adelavega** [comment]
For now, this will be a transformation that is implicitly added after all other transformations (and not shown in transformation tab). This could cause some clashes with model made in `pyns` but oh well (and should be less of an issue for simply reviewing models)

**Comment by rwblair** [comment]
#412 closed due to new direction
