### ISSUE TITLE
Add route or separate service that enables execution of analyses for privileged users

### ISSUE THREAD

**Issue by tyarkoni** [neuroscout/neuroscout#345]
Privileged meaning us.

**Comment by adelavega** [comment]
This could also be a internal library that we use to launch neuroscout tasks on our server and could interact with the `pyNS` library.

Either way, adding user classes is probably a useful thing down the road.

**Comment by adelavega** [comment]
I'm going to close this for now, since we have a fairly smooth workflow using `ssh` and `pyNS`. I don't think its worth the security risk / load balancing on celery to enable this. If this seems like a good option down the road we can re-consider it.
