### ISSUE TITLE
Allow failed analyses to be deleted

### ISSUE THREAD

**Issue by adelavega** [neuroscout/neuroscout#364]
Currently, only analyses in `DRAFT` mode can be deleted.

It seems fair to me to allowed `FAILED` analyses to be deleted, since they could never be run.

@tyarkoni would it bother you to allow this? Speaking from my own experience, sometimes I start from scratch rather than fix a broken/failing analysis, and it would be nice to be able to delete.

**Comment by tyarkoni** [comment]
Yeah that sounds reasonable.
