### ISSUE TITLE
Reports routes for review tab

### ISSUE THREAD

**Issue by adelavega** [neuroscout/neuroscout#378]
The goal will be the show modulate reports on the review tab.
To do this, we have to decouple `/analysis/compile` and `/analysis/reports`
Instead, create many parallel routes on `/analysis/reports` that execute in parallel in the background (and are cahced).

Example sub-routes on `/api/analysis/{hash_id}/{}`
- Transformations
- Events
- Diagnostics
- Description
- Design Matrix

At first, could return dummy results for these, but at least define API for @rwblair to begin building Review tab #328

**Comment by adelavega** [comment]
@effigies, @tyarkoni and I discussed showing users interact reports of their BIDS model design prior to analysis execution. Since reports will be generated on designs prior and during execution in `fitlins`, it naturally suggests reports should be modularized outside of fitlins execution per se. 

Would it make sense to put these reports into `bids.analysis`, which then `fitlins` and `neuroscout` can both use independently?

**Comment by effigies** [comment]
I'm okay with that, though pybids is starting to get pretty heavy...

**Comment by tyarkoni** [comment]
In a sense, pybids already supports this; the main thing we'll want to show users is the design matrix, and fitlins is already getting that via `get_design_matrix` anyway. The only thing pybids doesn't do for you (and probably shouldn't) is visualize the design matrix as an image. But once you have the design matrix as a `DataFrame`, you can just standardize the columns and show the whole thing as a heatmap, and that would be perfectly adequate for our purposes.

That said, I think rather than adding parallel calls from NeuroScout to pybids, it would probably be easier if fitlins just wrote an image of the design matrix out to disk, and NeuroScout could just grab that and display it.

**Comment by adelavega** [comment]
Well, I rather conceptualize it as decoupling some of fitlins reports generation from the actual execution / nipype, so that the call the generate these reports is as light as possible. 
That is, I could just import from fitlins the functions I need (and maybe theres a higher level call that generates several reports at once)

I have taken a look at fitlins code, but maybe that's already the case.

**Comment by effigies** [comment]
The nipype interfaces are very thin wrappers on regular functions.

Visualization functions are here: https://github.com/poldracklab/fitlins/tree/master/fitlins/viz

**Comment by adelavega** [comment]
Perfect. Maybe I should looked first.... :)

**Comment by adelavega** [comment]
Thinking about reports some more, the issue that stands out the most for me, is that the design matrix that is output by pybids (e.g. `block.get_design_matrix`), is not the exact same as the final design matrix used in model fitting, because there are some implementational details in `fitlins` `nistats` that determine the final product (e.g. densifying spare events, or not, cosines, anything else that `nistats` does in `dm.make_design_matrix`

I think in neuroscout we'd like to output the closest thing we can to a final product. That argues for modularizing the steps in fitlins that go from pybids -> final design matrix, so that it would be easy to import that function, apply it to a pybids `Analysis` and get something close to the final design matrix, which I can then generate other reports on (covariance, a plot like in fitlins, etc..)

Thoughts? Should that go in `fitlins`? Should more be abstract into `pybids`?

**Comment by tyarkoni** [comment]
I think the plan is to move virtually all of the DM construction stuff out of fitlins and into pybids, so I don't think this will be an issue long-term. Actually, I'm not sure what can't already be handled by pybids; if the HRF is being handled as a transformation, you should be able to call something like `get_design_matrix(mode='dense', sampling_rate=0.5)` and get back a strictly dense-format matrix with convolution applied and resolution downsampled to the TR (assuming in the above example that the TR was 2 seconds). If there's anything that fitlins or nistats are doing right now that pybids isn't, we can probably live without it for the moment, and eventually move that into pybids as well.

**Comment by adelavega** [comment]
That sounds good to me. The "extra" things fitlins does are relatively minor, so that shouldn't be too much trouble to migrate over, or drop (e.g. adding `cosines` if none are found in model)

**Comment by effigies** [comment]
The whole cosine default is a bit problematic, especially if we start getting data from non-fMRIPrep pipelines. It would be kind of nice if logic like "if using \*CompCor\*, then include Cosine\* columns" could be included in pipeline outputs.

**Comment by adelavega** [comment]
Closed w #382
