### ISSUE TITLE
Make frontend form validation more explicit to user.

### ISSUE THREAD

**Issue by rwblair** [neuroscout/neuroscout#389]
Traditionally html form validation will complain when a form is being submitted. Need to trigger this action when the next tab button is hit.

**Comment by adelavega** [comment]
https://axesslab.com/disabled-buttons-suck/

**Comment by adelavega** [comment]
I think the *only* place this is left is in the Contrast panel. If we could enable the OK button and warn users of incorrect form usage, we could close this issue @rwblair
