### ISSUE TITLE
X failing to display in review

### ISSUE THREAD

**Issue by adelavega** [neuroscout/neuroscout#405]
@rwblair this is probably my fault for messing w/ the BIDS StatsModel representation, but X is failing to display in the review mode. Can you take a look? Thanks

**Comment by tyarkoni** [comment]
Should this be closed? It still doesn't show up (or maybe it did, and this re-broke).

**Comment by tyarkoni** [comment]
Oh, nevermind. It does show up, but it looks like it takes a really long time (i.e., after the other stuff has loaded), for some reason.

**Comment by tyarkoni** [comment]
Okay now there isn't even any delay. Not sure what's going on here. @adelavega, is it possible that the value is cached the first time it's displayed, but it takes a while to populate?
