### ISSUE TITLE
Show authors for public analysis listing

### ISSUE THREAD

**Issue by adelavega** [neuroscout/neuroscout#417]
But what should be shown? Display name? email?
Email is too private, but display name needs to be set.

We need to force users to choose a display name (not user name). We could auto generate one based on their email, but allow them to edit it via "My Profile" (#159)

**Comment by rwblair** [comment]
Fortunately we can get a nice display name from the google auth. Maybe we add a field in signup for a display/user name?

**Comment by adelavega** [comment]
Closed with #791
