### ISSUE TITLE
Show number of subjects for dataset listing

### ISSUE THREAD

**Issue by adelavega** [neuroscout/neuroscout#418]

**Comment by adelavega** [comment]
I can also easily calculate this "on the fly" as a property. I doubt it should be too slow especially with caching.

**Comment by rwblair** [comment]
yeah thats probably the easiest way, didn't know how inefficient it would be. Guess it would be done in all through python?

**Comment by adelavega** [comment]
Yeah, and with caching it should be okay, although we should keep #475 in mind.
