### ISSUE TITLE
Add auto-populated summary of compiled analyses

### ISSUE THREAD

**Issue by adelavega** [neuroscout/neuroscout#422]
For compiled analyses, the review tab should be the default landing page

Let's add a the very top a short summary of the analysis. This could be a text summary that is auto populated.

Minor points:
- Variables
  - Add description next to "X" e.g. "Variables"
  - Lets put them in a table, it will get too long as its currently listed
- Json Model -- Call it full BIDS-StatsModel

**Comment by rwblair** [comment]
I still need to add the summary of the analysis.

**Comment by adelavega** [comment]
Update: I think a auto-generated text, or a small table summarizing the dataset / # of subjects / # of runs / # of predictors (# of confounds?) would be great. I'll think about this some more and put together a prototype, maybe this can actually be provided by the backend in #478

**Comment by adelavega** [comment]
I'm going to close this in favor of #478
