### ISSUE TITLE
Progress indicator when preparing analysis

### ISSUE THREAD

**Issue by Shotgunosine** [neuroscout/neuroscout#452]
When the analysis is being prepared its not clear how much longer it's going to take or if there's been a problem. Some indicator of progress or position in the queue till processing starts or something like that would be helpful.

**Comment by adelavega** [comment]
This might be a bit hard to do, because its hard to know how long it'll take, and how to communicate that from celery back to the server.

**Comment by adelavega** [comment]
I'm going to close this because it seems really hard to get progress updates from celery. On the plus side, compilation is way faster now, because HRF has been sped up 10-100x.
