### ISSUE TITLE
Design matrix still not showing up for already-generated analyses

### ISSUE THREAD

**Issue by tyarkoni** [neuroscout/neuroscout#453]
When reviewing existing models, the design matrix never shows up—the "loading" icon just spins endlessly.

**Comment by adelavega** [comment]
@rwblair I think this is a relatively high priority bug. Can you reproduce such behavior?

**Comment by rwblair** [comment]
I believe so: https://alpha.neuroscout.org/builder/Mm7Xw

This just gets 404s when attempting to load the report. If user is logged in and they own the analysis we'll issue a POST to generate image. What do we want behavior for non owners or not logged in users to be? Should there be a POST route to generate image that does not require login?

Also theres a bug where a public analysis asks for login when viewing review tab that I need to fix.

**Comment by rwblair** [comment]
Ran my local front end against /builder/Mm7Xw and the report ended up getting generated, and now loads for  https://alpha.neuroscout.org/builder/Mm7Xw instead of the 404s I was seeing initially.

**Comment by adelavega** [comment]
Ah, good point about the permissions. I suppose we could make it such that for public reports that are in `PASSED` state, anyone can generate a report if there already isn't one (and in most cases there should be one). 

Alternatively, we could gracefully not display it, asking them to log in.

**Comment by adelavega** [comment]
Hmm, you are right, I'm not seeing this issue myself either. Maybe it was only an issue with nonauthorized users, so we can narrow this bug down to that. 

Maybe for now we can just ask users to log in and siplay a nice message instead of messing with the API (I don't like the idea of anonymous users requesting background jobs).

**Comment by tyarkoni** [comment]
I don't see a problem letting anyone who has access to an analysis (whether logged in or not) generate results. Assuming we're memoizing images/results, the worst that can happen is that an unauthenticated hits every possible route once. But that seems wildly unlikely, and anyway if someone's determined to screw us that way, it's not like creating a throwaway account is going to be a barrier.

**Comment by adelavega** [comment]
Okay that's easy enough to do then.
