### ISSUE TITLE
/api/ should show swagger docs

### ISSUE THREAD

**Issue by tyarkoni** [neuroscout/neuroscout#472]
Assuming we're still using Swagger to generate API docs, the `/api/` route should display the standard swagger landing page (or at least, some kind of documentation for the API)

**Comment by adelavega** [comment]
This is currently where it's at. Should be doable to move it: `https://alpha.neuroscout.org/swagger-ui/`

**Comment by tyarkoni** [comment]
Yeah, let's move it (or aliasing is also fine). `/api/` currently returns 404, so there's no cost, and users are naturally going to look in `/api/` first.
