### ISSUE TITLE
parameters missing in swagger-ui docs

### ISSUE THREAD

**Issue by tyarkoni** [neuroscout/neuroscout#474]
Some of the swagger-ui docs are missing key parameters (e.g., the `predictors` route doesn't show the `run` argument). Should probably be updated.

**Comment by adelavega** [comment]
Is that true? I see `run`

**Comment by adelavega** [comment]
![image](https://user-images.githubusercontent.com/2774448/52002235-13a0c900-2487-11e9-9321-541d20c62f58.png)

**Comment by tyarkoni** [comment]
Time for the annual eye exam...
