### ISSUE TITLE
Display dataset info on Review page

### ISSUE THREAD

**Issue by tyarkoni** [neuroscout/neuroscout#498]
This is related to #449, but probably merits its own issue. Currently when reviewing an existing analysis, it doesn't seem like there's an easy way to tell what dataset was used. I know that this isn't part of the BIDS-StatsModel spec, so maybe it shouldn't be shown in the accordion, but it does need to be displayed somewhere.

**Comment by adelavega** [comment]
Yes, I think a more comprehensive summary (maybe even in semi-prose) would be useful.

**Comment by adelavega** [comment]
Hey @rwblair I'll add to this issue that it would be great if you could see the dataset in the listing as a column. It would make it way easier to know which analysis is which (especially if you cloned and switched datasets)
