### ISSUE TITLE
Shorten author list

### ISSUE THREAD

**Issue by adelavega** [neuroscout/neuroscout#501]
For aesthetic purposes, it would be nice to shorten the author list such that if there are more than 3 authors, only the first and last are shown, with "..." in between.

Minor easy issue.

**Comment by rwblair** [comment]
We ever expect authors to have a comma in their names?

**Comment by adelavega** [comment]
Well, yes in that sometimes its "Last Name, First"

**Comment by rwblair** [comment]
Whale that was real dumb of me. Updated PR to handle this.
