### ISSUE TITLE
Align DM labels with middle of column, not left edge

### ISSUE THREAD

**Issue by tyarkoni** [neuroscout/neuroscout#531]
This is the most pedantic issue anyone will probably ever open here, but the vertical alignment of design matrix column labels appear to be off—it's somewhere between the left edge and the center, instead of being exactly in the center. This is obviously not a high priority, but on the other hand, it may be a trivial fix.

Example:
![image](https://user-images.githubusercontent.com/303932/55365863-cbfce480-54ab-11e9-8689-fc9966a62743.png)

**Comment by adelavega** [comment]
Blame nistats, I'm using their function!

But actually, yes I'll take this into consideration when tweaking the vega-lite plots as I'm making those from scratch, just emulating the nistats plots.
