### ISSUE TITLE
Allow user to select subject/run to display design matrix for

### ISSUE THREAD

**Issue by tyarkoni** [neuroscout/neuroscout#533]
I could have sworn there was an open issue for this, but maybe we only discussed it in person. Anyway, on the review page, it would be nice to let users choose which run/subject they want to display the design matrix for (and have it generate in real time if not already cached).

**Comment by adelavega** [comment]
Yes, this has been on the low-priority road map, but maybe got lost in the issue tracker.

The API currently supports specifying run(s) for reports (actually, by default, the frontend is specifying the first run)

**Comment by adelavega** [comment]
In #571 I added the ability to request if plots should be scaled for display purposes. We should probably add this as an option to the user when we implement this.
