### ISSUE TITLE
How do we handle constant/empty columns?

### ISSUE THREAD

**Issue by tyarkoni** [neuroscout/neuroscout#534]
It looks like if the user adds a column that has all 0 values for a run, it's retained in the design matrix. This is likely to cause us a bit of a headache at some point, as the appropriate handling is probably to drop the column if it's missing for *all* runs, but keep it if it has values for some but not for others. Do we currently do anything about this?

A related issue is that retaining constant columns assumes that fitlins/nistats can actually handle such columns without crapping out. Have we verified this?

Ultimately it's the user's responsibility to make sure their model makes sense, so it isn't the end of the world if we don't do anything about this on the back end. But it might not be a bad idea to at least emit a front-end warning of some kind.

**Comment by adelavega** [comment]
This was a problem in the past with face probability in the Life dataset. I think a warning is a good idea. I think this is a general type of thing we need to add to the reports module. 

I'm pretty sure fitlins will crap out if any given run has all zeros. Actually, I think this might even happen upon compilation, so I think a strong warning is warranted.

**Comment by adelavega** [comment]
This should be handled with #441

**Comment by adelavega** [comment]
In #542 I made it so that by default Predictors are only created if present in 90% of runs (which is basically 100% in all cases, so I should have just set it to that).

This default should prevent this problem, although it's still good to add a check in #441.

**Comment by adelavega** [comment]
Closing in favor of #441
