### ISSUE TITLE
Disable Predictors not present across all runs by default

### ISSUE THREAD

**Issue by adelavega** [neuroscout/neuroscout#541]
Given that:
1) Fitlins can't handle empty predictors in a run
2) For some extractors there are potentially way too many features (1000s)
3) The frontend struggles a bit (at least in terms of UX) with so many features

I suggest that by default, when extracting, if a feature is not present in all runs, it is not `active` by default. We could de-active at the feature or predictor level (e.g. not create a predictor at all, or create it, but not display it by default. Given that it takes a long time to create features, I would at least suggest for those not present in 50-80% of runs, they are not even created.

**Comment by tyarkoni** [comment]
Seems reasonable to me. I assume you'll log somewhere centralized that a feature was skipped because of missingness, so we don't unnecessarily re-extract it with pliers every time there are incremental changes.

**Comment by adelavega** [comment]
Yes and no. The `ExtractedFeature` (which is in "stimulus" time) it self will be created and stored, but a `Predictor` (with "run" timing) won't be created. This means we could always create the `Predictor` from the `ExtractedFeature` if we wanted to. But I think most incremental updates with re-extract everything anyways, if we re-run that extractor.
