### ISSUE TITLE
Return 404 instead of 401 if user has no access to resource

### ISSUE THREAD

**Issue by tyarkoni** [neuroscout/neuroscout#549]
This is a very minor security concern, but given that we're practicing security through obscurity, I think we should probably return 404 (instead of 401) for all API requests that a user doesn't have permission to access ([e.g., here](https://github.com/neuroscout/neuroscout/blob/92e7c7e18a0d62e65f9427addf20a3a4d8c39a9e/neuroscout/resources/utils.py#L92)). This prevents us from disclosing whether or not a resource (e.g., an `Analysis` actually exists at that URL).

**Comment by adelavega** [comment]
Luckily since that is the main decorate to handle that, it should be a trivial change.
