### ISSUE TITLE
Profile Celery

### ISSUE THREAD

**Issue by adelavega** [neuroscout/neuroscout#582]
The main downside I'm observing since moving the database to celery is that its taking longer (or so it seems) to generate reports. Maybe the database connection / flask initialization overhead is actually worse than it seems.

**Comment by tyarkoni** [comment]
Does it have to spin up the app on every request, or just once when the worker is launched?

**Comment by adelavega** [comment]
I think it may launch a new worker whenever a task is received, given this issue. Maybe there's a way to preload workers with initalized db / flask / imports. The difference is not that bad, by the way. But it was noticeable especially for reports (which were loading quite quickly before).

Worst case scenaro, I can go back to doing db operations for reports on the main app, since it was not that heavy one run at the time. For compilation (which requires all runs), I could keep it on Celery.

**Comment by tyarkoni** [comment]
It shouldn't be launching a new worker each time... Workers should be running as a daemon in the background (see `celeryd`), initializing the DB once (per worker), and fielding requests on-the-fly via redis (or whatever other queuing mechanism you're using). Aside from creating new opportunities for failure, spinning a new Flask app and DB connection up on each request is probably not going to be super scalable.

**Comment by adelavega** [comment]
Well that's the way it's supposed to be set up, so I'm not sure why it would be taking any longer than the previous set up. Maybe I need to ensure enough workers are pre initialized.

**Comment by adelavega** [comment]
Let's restore the monitor also

**Comment by adelavega** [comment]
Well, good news and bad news.

I set up a dummy "sleep" task in which you could specify the # of seconds before the task was completed. The task also used the db to retrieve a random analysis.

Even running 5-10 concurrent tasks, the workers finished in ~10.1 seconds, which leads me to think that Flask overhead is not a problem, and instead, we the bottle neck is just pybids related, and theres not too much we can do about it. 


OTOH, reports only take 15-30 seconds to generate for simple design, so this is not *that* bad. Just not as snappy as I'd like (<10 s)
