### ISSUE TITLE
t.filter is not a function error when unselect all runs

### ISSUE THREAD

**Issue by adelavega** [neuroscout/neuroscout#590]
This happens only once when unselect all subjects

**Comment by adelavega** [comment]
This issue will be closed when we refactor the run selector component (i.e. have a separate apply picker, rather than using the filters in the table)

**Comment by rwblair** [comment]
I'm having trouble recreating this, what dataset did you see it on?

Should we replace the analysis builder run selector with the one in the predictor collection creation form?
