### ISSUE TITLE
not all predictors visible in design matrix

### ISSUE THREAD

**Issue by koudyk** [neuroscout/neuroscout#594]
In the 'Review' section, not all the predictors are visible in the design matrix:

![Screenshot from 2019-06-08 12-03-41](https://user-images.githubusercontent.com/39495291/59145533-85fd5900-89e5-11e9-8bbc-0259d54e563e.png)

Here's the link to the analysis:
https://alpha.neuroscout.org/builder/wlEWA

**Comment by koudyk** [comment]
Actually, it's probably an issue specific to the spectral_centroid feature. It might be related to how this feature is calculated for every sample.

**Comment by adelavega** [comment]
Thank you! I've disabled "central_spectroid" for now, and will re-extract later
