### ISSUE TITLE
suggestion: add filters to predictors search

### ISSUE THREAD

**Issue by koudyk** [neuroscout/neuroscout#595]
It might be helpful to add filters to the predictors search. For example, one could check a box to see only the auditory predictors. 

Having these checkboxes might also make it more obvious that you can select confounds from fmriprep, if there were a filter for fmriprep.

**Comment by adelavega** [comment]
@tyarkoni I think we should consider something like this that allows people to explore/discover the categories of predictors better. It's probably one of the most consistent bits of feedback I've received -- selection predictors can be a bit overwhelming even with good full text search.

**Comment by adelavega** [comment]
An alternative is to have the search do predictive fill in like google does, and have certain "tags" get locked in once you type them.

e.g. if you start typing `audi...` `audio` would be an option and would become a tag that is in the search bar (with an x to remove).

**Comment by adelavega** [comment]
I'm going to close this in favor of #695 as they are very similar.
