### ISSUE TITLE
Interface for uploading for custom annotations

### ISSUE THREAD

**Issue by adelavega** [neuroscout/neuroscout#603]
Related to #589 , we need a general way to upload custom annotations for datasets. 

For `ParanoiaStory` there were also some annotations that @esfinn said she had. If users were able to upload these through the web interface, that would be ideal.

**Comment by esfinn** [comment]
Happy to provide these whenever in any format(s) might be useful for testing, lmk

**Comment by adelavega** [comment]
Had a conversation with @rwblair about this and I think the solution we'll go with is:

API Endpoint to `/api/predictor/create`

with takes:
- Predictor meta-data
- multi-part form list of event files with annotation (length of N)
- list of runs for which the files apply to (length of N)

The API user needs to specify which runs each file applies to, since currently there is no concept of which subjects saw what (e.g. did all subjects see the same stimuli, or were there between subject conditions?)

Need to ensure we can do a multi-file multi-part form upload, but if so this should work.

On the frontend, we'll create a file uploaded which makes it easy to use filters (e.g. `run_ids` and `subject_ids`) to populate the API form. We could also compute the unique sets of runs to make it easier to match annotations to sets of runs.

**Comment by tyarkoni** [comment]
All sounds good to me.

**Comment by adelavega** [comment]
Some additional features we want to implement:

- Private/Public status for created Predictors. By default, they should be Private, and there should a vetting process to make them public. This requires thinking about the `/predictors` route to take an optional JWT to get user identity (and/or, getting private predictors a different way, through `/user` maybe)
- Given the above, we also want to show a timestamp for when Predictor was created in the table

**Comment by adelavega** [comment]
Also

**Comment by adelavega** [comment]
hey @esfinn, whenever you get a chance, feel free to send me some of your manual annotations. I'm ready to upload them to NeuroScout. The preferred format is "long" format, with one row per timepoint. The two mandatory columns are "onset" and "duration". 

If they're not already in that format, you could send them to me however you have them and I'll reshape them :)

Thank you!

**Comment by adelavega** [comment]
Closed with #631
