### ISSUE TITLE
displaying more dataset info in analysis builder

### ISSUE THREAD

**Issue by rbroc** [neuroscout/neuroscout#689]
It might help to be able to see more details on the available datasets when you have to select them in neuroscout.org analysis builder. </br> Could be useful to expand the **datasets table** displayed in the **analysis builder** , potentially adding: 
- more systematic info on which modalities are available in the dataset (e.g. a yes/no value coding for presence of "auditory", "visual", "speech" info)
- duration
- TR and/or number of TRs per subject
- tasks (passive viewing/listening or other)
- dataset id used to retrieve dataset details when accessing API via pyNS
- when dataset is a subset of the linked dataset, pointer to how and why this has been done 
- reference to most relevant paper?

**Comment by rbroc** [comment]
possibly specify summary demographics (gender ratio, age, handedness, healthy/patients), either as separate field in table or just in the dataset description. 
One option would be to just specify this info when sample is "abnormal" in some respect.

**Comment by rbroc** [comment]
Maybe add a separate tab or pop-up menu on acquisition sequence (TR, spatial resolution, etc.)

**Comment by adelavega** [comment]
- Authors: Remove as column, or make First author et al.,:
- Add modality as a column (in back end, add friendly modality name) (For now, have only 1 per dataset, but once we have more, you can sort by first)
- Move link to +

**Comment by adelavega** [comment]
Move task information, or at least list task specific information in Dataset information table

**Comment by adelavega** [comment]
For demographics, for now either show summary statitics, or point to a more info in docs, or original dataset docs.

**Comment by rwblair** [comment]
includes a fix for #692 where the total number that will ever be displayed is only the number of runs for that task instead of all all runs for dataset.
