### ISSUE TITLE
ComplexText Stimulus Representation

### ISSUE THREAD

**Issue by adelavega** [neuroscout/neuroscout#713]
A general problem we haven't solved yet is how to tokenize force aligned stimuli to take into account context.

Currently, all extracted events (EEs) are generated from a single stimulus a time.

For example, when we compute the frequency of a word, we do it on a word-by-word basis (1-to-1 mapping between stimulus and EE).

We also have situations where a single stimulus results in a multiple EEs. For example, `shot_change` is applied to a single video file, but results in multiple EEs (1-to-many).

For speech, we would like to be able to get features at the temporal resolution of the force aligned text, but that take into account the context occurring prior and after the word. For example, if there was a pliers extractor that computes the number of times a word has occurred in the movie so far (this would be a many-to-many mapping).

For a similar situation (face_net, `first_time_face`), we solved this by operating entirely outside of pliers/neuroscout and just uploading a custom `PredictorCollection`. 

I think the solution here is to have a `ComplexText` type of Stimulus representation that groups together individual words, with individual onsets, but has a single RunStimulus association back to Predictor time. 

This would require an additional table in the database that keeps track of the individual words and their onsets, and maps them to a single `Stimulus` entry of type `ComplexText`.

Alternatively, we could save these "tokenizations" as .tsv file which are read in by pliers as `ComplexTextStimuli`, but I think I would rather represent these as a new table in the db.

This should allow us to tokenize all the speech in a run, or even a while movie across runs, and then map that back into Predictor / original "functional" time like we do with any other stimuli. 

We could need to create some functions to create these "tokenized"/"grouped" ComplexText Stimuli from individual words with onsets in the db.

**Comment by adelavega** [comment]
WDYT, @tyarkoni? I think this is actually fairly doable and should let us extract more interesting speech features w/ context.

**Comment by tyarkoni** [comment]
Wouldn't this be more easily solved by writing a pliers extractor that takes `ComplexTextStim` inputs and produces a pandas DF with word-level onsets? I guess I'm not clear on why we'd want to do this outside of pliers. A `TextStim` can have an onset and duration specified, so we don't lose track of those when we embed them in `ComplexTextStim`s—so they're available to a transformer to do whatever it needs to with them. Either way you'd still need to define the context appropriately (e.g., to tokenize at the sentence level instead of word level), but it makes more sense to me to keep that inside pliers.

**Comment by adelavega** [comment]
I'm saying this goes in hand with that. This would be for pliers extractors that take in `ComplexTextStims` and output word-level onsets.

But we need to have something that creates that `ComplexTextStim` in the first place, as in Neuroscout all extraction is done on single stims and single extractors. And we currently represent intermediary stimuli explicitly in the db, rather than letting pliers do its auto-magic conversion. So I think it would make sense to represent explicitly these tokenized `ComplexTextStims`. The thing that does the tokenization could also be a pliers converter, but I'm suggesting how to store that output prior to extraction.

**Comment by tyarkoni** [comment]
I'm probably misunderstanding something, but I still don't see why the CTSs needs to be stored in the DB... I get that there has to be code somewhere that groups the word tokens into CTSs, but what's the benefit in storing the CTS-level objects in the DB? The actual predictor values are always at word level, right? So in effect we'd have an extra join table that only tells us which word belongs to which CTS, even though that isn't really used anywhere else. I'm not necessarily against it, I just don't know what it buys us.

OTOH, if there are features we want to include that *aren't* available at word level, then I think that would be a reasonable justification for a CTS representation...

**Comment by adelavega** [comment]
I guess you're right it may not be something we need to do in the database. It would just fit the convention we currently we have of representing intermediary stimuli in the database.

Same as when we store the intermediate `FrameSamplingConverter` outputs in the database, rather than letting Pliers apply that converter. I suppose in that case it buys us not having to re-run the converter again, whereas theres very little computational cost of re-running the tokenizer. 

Actually if we don't need to store in `db` it makes my job easier, so I'm happy with that. We just need to add a mechanism into Neuroscout that allows us to specify the tokenization step that occurs immediately prior to an extractor that requires it. Currently, extractors are applied to a single stimulus at a time, so we need to change that as well, so more generally speaking that is what is missing.

**Comment by tyarkoni** [comment]
I'm fine either way, it's mostly just a question of how much effort is involved. I do think it's worth considering whether there are any variables we'd want to extract that *only* get extracted at the CTS level. Because if there are, that would argue for a DB representation. E.g., if we can only get sentiment norms for sentences, then we would want to store the sentences in the DB with onsets, durations, etc. And if we're doing *that*, then at that point it seems trivial to add a mapping from words to CTSs.

**Comment by adelavega** [comment]
Yeah, I think we could use this for any Extractor that requires tokenization to make sense. This is also true for the `WordCountExtractor` (only makes sense if you're actually counting across a run).

We can think more about this when we get back, but yeah it looks fairly easy.

One minor concern (mostly not to self) is currently Neuroscout greedily applies extractors to all matching stimuli (e.g. applies video extractors to all video stimuli for a dataset). For `ComplexTextStimuli`, not all tokenization are going to make sense for all extractors. For example it may not  make sense to apply word counter to sentence level tokenizations. But for some we might want to apply to multiple tokenizations, as the differences may be interesting.
