### ISSUE TITLE
TypeError:...unexpected keyword argument 'dummy_contrasts'

### ISSUE THREAD

**Issue by rschmaelzle** [neuroscout/neuroscout#714]
Hi,
I've been playing around with Neuroscout successfully in the past, but since i tried last time, something seems to have changed. Now, after running a preconfigured analysis pipeline i(from November/December) via the Docker, it breaks with the error: 
TypeError: __init__() got an unexpected keyword argument 'dummy_contrasts'
It seems that the web-service has been changed in a way that the Docker doesn't know yet?
Best, Ralf

**Comment by adelavega** [comment]
Hi Ralf, 
Thanks for this. 

We have recently updated the way the models are internally represented.

One of the major changes was the `auto_contrasts` are now called `dummy_contrasts`.

Try pulling the latest version from Docker, it should have the updated code.

`docker pull neursocout/neuroscout-cli`

let me know if that doesn't work. That makes me realize however, that I forgot to update the minimum version required for the ported models. Ideally, you should have gotten an error that told you to upgrade the CLI and pull the latest image. I'll look into why that didn't happen.

**Comment by rschmaelzle** [comment]
Hi Anthony, thank you very much again! That was it: docker pull ... - I should have thought of that.
Thank you and best, R
