### ISSUE TITLE
Cannot sign in via google oauth

### ISSUE THREAD

**Issue by satra** [neuroscout/neuroscout#726]
when logging in via google the sign in page does not change or log me in after i authorize google.

**Comment by adelavega** [comment]
Do you have adblockers or privacy badger enabled?

I just tried it and it didn't work for me until I disabled those two :/

**Comment by adelavega** [comment]
Specifically Privacy Badger seemed to be breaking it for me. Just tested each individually.

**Comment by satra** [comment]
thank you @adelavega  - it was my various blockers!! 

i use brave and i now trust neuroscout to not do anything dangerous, and i know that is dangerous by itself !!

**Comment by tyarkoni** [comment]
NeuroScout definitely presents a danger, but more to our server than to your laptop. :)
