### ISSUE TITLE
How to handle categorical variables?

### ISSUE THREAD

**Issue by adelavega** [neuroscout/neuroscout#728]
Currently, categorical variables are displayed in the predictor list, such as `headwearLikelihood`

Pybids will crash on these variables, because they cannot be coerced to a numeric value with the error:

```
 Error:The Convolve transformation does not allow variable 'headwearLikelihood' to be categorical. Either pass a different variable or explicitly convert to a set of binary indicators via the 'factor' transformation.
```

This is not very useful, because the `factor` transformation is not available as it requires knowing the values of the variables to know the names of the new columns created. 

Some possible solutions to handle categorical variables include:

1) Removing them from the Predictors listing
2) Adding pre-computed transformations for these variables, such as a linear coding, either alongside or instead of the raw variable. 
3) Add a warning at the Review stage that warns users that these variables are not usable in the web app (and maybe instead use pyNS).
4) Adding a categorical indicator, that links to documentation on how to use these variables using `pyNS`. We could have a mini tutorial on how to inspect the values and how to use `factor` or `replace` to code the variable

Finally, if we really wanted to add this functionality to the web app, here's a potential implementation:
We could pre-compute the unique variables in categorial variables (and potentially show a histogram), and use this to prepopulate a Replace transformation. The user would then have to map each unique variable to a new variable. 

If this operation is done in-place, it would not require keeping track of new variables.

**Comment by tyarkoni** [comment]
IMO, (3) is definitely out for the web UI—there's no point in saying "in theory you could use this, but actually, you can't".

I'd lean towards (2) if we can do it in a sane way; my worry is we'd have to do a lot of experimentation and then we're taking responsibility for the transformation. So this is probably not good either.

I'd say we go with a combination of (1) and (4). Maybe automatically hide categoricals from the web listing, but keep them in any centralized documentation of all predictors (assuming we have such), and explain how to use them in PyNS.

**Comment by adelavega** [comment]
Yeah, @rbroc felt similarly about (3). It's kind of a tease and frustrating.

Your suggestion would be fairly easily to implement. We could add a `hidden` property (or maybe even explicitly `categorical`) , such that variables are still returned in the API query, but the frontend hides them for the user (this way pyNS still sees them). 

My main concern is I think users won't discover these variables, if they're just listed in the docs.

**Comment by adelavega** [comment]
Okay, let's add a flag for returning categorical variables to the API, and the frontend won't display them by default. 

We can worry about the `Replace` transformation in the future, if there is a request for it.
