### ISSUE TITLE
issue with face emotions features

### ISSUE THREAD

**Issue by rbroc** [neuroscout/neuroscout#735]
Emotions predictors from google face detection for HealthyBrainNetwork, Raiders and Life not detected when querying via pyNS,

**Comment by adelavega** [comment]
Only the following datasets have the `joyLikelihood` feature (for example):

```
[<models.Dataset[name=LearningTemporalStructure]>,
 <models.Dataset[name=Sherlock]>,
 <models.Dataset[name=studyforrest]>,
 <models.Dataset[name=SherlockMerlin]>,
 <models.Dataset[name=SchematicNarrative]>,
 <models.Dataset[name=generic_object_decoding]>]
```

So looks like that is the reason
