### ISSUE TITLE
Error when running SherlockMerlin data

### ISSUE THREAD

**Issue by jsmentch** [neuroscout/neuroscout#749]
I'm running into a problem where my analysis will not run on the SherlockMerlin data.

There is a FileNotFoundError and the sym link it is pointing to 
`SherlockMerlin/preproc/fmriprep/sub-01/anat/sub-01_desc-brain_mask.json`
is there, but the file that is being linked to
`../../../.git/annex/objects/1q/xq/MD5E-s80--9af69ab10f32a7be2158968efa8b5869.json/MD5E-s80--9af69ab10f32a7be2158968efa8b5869.json
`is not.

 
I am using the SherlockMerlin dataset and this is the error I am receiving:

```
INFO:root:Running analysis : wJ3jb
INFO:root:Bundle installed at /om/user/jsmentch/neuroscout/sc/cache/SherlockMerlin/neuroscout-bundles/wJ3jb
[INFO] Cloning https://github.com/neuroscout-datasets/SherlockMerlin to '/om/user/jsmentch/neuroscout/sc/cache/SherlockMerlin/preproc'
INFO:datalad.distribution.clone:Cloning https://github.com/neuroscout-datasets/SherlockMerlin to '/om/user/jsmentch/neuroscout/sc/cache/SherlockMerlin/preproc'
^MTotal:   0%|          | 0.00/505 [00:00<?, ?B/s]^MTotal: 100%|██████████| 505/505 [00:02<00:00, 186B/s]^MTotal (1 ok out of 1): 100%|██████████| 505/505 [00:02<00:00, 186B/s]^M                                                                     ^M\
Traceback (most recent call last):
  File "/src/neuroscout/neuroscout_cli/commands/install.py", line 68, in download_data
    layout = BIDSLayout(self.preproc_dir, derivatives=self.preproc_dir)
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/bids/layout/layout.py", line 277, in __init__
    reset_database=index_dataset or reset_database
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/bids/layout/layout.py", line 780, in add_derivatives
    self.derivatives[pipeline_name] = BIDSLayout(deriv, **kwargs)
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/bids/layout/layout.py", line 262, in __init__
    indexer.index_metadata()
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/bids/layout/index.py", line 202, in index_metadata
    with open(bf.path, 'r') as handle:
FileNotFoundError: [Errno 2] No such file or directory: '/om/user/jsmentch/neuroscout/sc/cache/SherlockMerlin/preproc/fmriprep/sub-01/anat/sub-01_desc-brain_mask.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/miniconda-latest/envs/neuro/bin/neuroscout", line 11, in <module>
    load_entry_point('neuroscout-cli', 'console_scripts', 'neuroscout')()
  File "/src/neuroscout/neuroscout_cli/cli.py", line 62, in main
    command(deepcopy(args)).run()
  File "/src/neuroscout/neuroscout_cli/commands/run.py", line 21, in run
    bundle_path = install.run()
  File "/src/neuroscout/neuroscout_cli/commands/install.py", line 107, in run
    return self.download_data()
  File "/src/neuroscout/neuroscout_cli/commands/install.py", line 82, in download_data
    message = e.failed[0]['message']
AttributeError: 'FileNotFoundError' object has no attribute 'failed'
```

**Comment by jsmentch** [comment]
I've edited this post: I get the same error regardless of running one subject vs all subjects. I'm able to run the studyforest data without trouble with the same settings. I was also trying to run the Sherlock dataset but it would take many days and never complete with the following warning repeated 8 times: 
```
WARNING:cli:Captured warning (<class 'DeprecationWarning'>): sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this \
warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
```

I'm not sure why I cannot run the Sherlock or Sherlock Merlin data but could run the studyforest, if anyone has any ideas it would be greatly appreciated, thanks!


If it is helpful, I am using singularity 3.5.0 and the following command to neuroscout-cli

`singularity run -e -B /om/user/jsmentch/neuroscout/projects/sherlock_merlin/out:/out,/om/user/jsmentch/neuroscout/sc/cache/work:/work  /om/user/jsmentch/neuroscout/sc/cache/neuroscout-cli.simg run -w /work -c 30 -n disable /out 9BqzZ`

**Comment by adelavega** [comment]
thanks for the report, i will look into it! 

sometimes we don't catch these because for our lab's analyses we have cached all the data, so thanks!

**Comment by jsmentch** [comment]
For sure, thanks!

**Comment by adelavega** [comment]
OK, I replicated your problem (it was being masked for us by the  caching like I thought), and I'll work on a fix, thanks for the bug report!

**Comment by adelavega** [comment]
Looks like the issue is that there was a change in pybids such that it indexes all the meta-data in a dataset, which requires having all the JSON files. Previously, only relevant JSON files were being downloaded, but I'm making a change that will pre-fetch all of them.

**Comment by adelavega** [comment]
Ok, success! I was able to get your first analysis to run with that fix. I'll merge it, and cut a a new release.

For your issue with the `Sherlock` data do you have an ID? You can also try running with the `--verbose` flag. It's possible that `-c` is not working (I usually use the long form "--n-cpus=30"), otherwise I'm not sure why it would  hang (possibly memory issues, but the forrest dataset is more memory intensive?)

**Comment by adelavega** [comment]
I'm going to re-open this for now since I'm not sure we've resolved your second issue. 

v0.3.6 of neuroscout-cli should be on docker hub soon if you want to test it out. thanks!

**Comment by jsmentch** [comment]
Thanks, I am no longer getting that first error!

I've tried to rerun both of these analyses: AxkqV(Sherlock) and 9BqzZ (SherlockMerlin) with the new neurodocker iamge and "--n-cpus=30"

AxkqV(Sherlock) hit an error but I think it may be due to not enough memory. I was using 20G of memory. 

9BqzZ is still running now for a few days. I will now try the --verbose flag which I did not include and report back if that can provide some useful info to debug.

**Comment by adelavega** [comment]
Okay, great let me know what you find. That is longer than I'd expect given that you have a relatively simple analysis. If I have some free cycles, I can try running that analysis and see how it goes.
I would expect it it only take a few hours to run. 

I would not be surprised if memory was a problem, with that many parallel processes. Each process can take up to 6-8GB at peak memory usage. It averages much lower, but it could be higher.

There's a small chance there's something odd going on w/ singularity. We have not tested with singularity much, but in theory it should work. It's on our to-do list to officially verify that it works, though.

**Comment by jsmentch** [comment]
Ok, both seem to have run successfully now after I increased the memory. Thank you for your help with this!

**Comment by adelavega** [comment]
That's great! Thanks for the beta-testing. Feel free to raise more issues in the future, we're eager to make NeuroScout as user-friendly and approachable as possible.
