### ISSUE TITLE
Some analyses are much slower than others generating reports

### ISSUE THREAD

**Issue by adelavega** [neuroscout/neuroscout#755]
Reports are again agonizingly slow... maybe 300s sometimes for a simple model.

Need to look again as to how to speed this up and what the pinch points are

**Comment by adelavega** [comment]
An example of a very fast report: Life with speech regressor
A slow one is SherlockMerlin MerlinMovie with brightness regressor.

**Comment by PeerHerholz** [comment]
I experience the same with e.g. `MD1pV`: reports take minutes to load or don't show up at all. It includes `Study Forrest` with 8 `AudioSet labels`, 6 `motion` and `csf` regressors.

**Comment by adelavega** [comment]
Thanks for the report! My guess is that it has to do with how dense the predictors are, but im not sure

**Comment by PeerHerholz** [comment]
If I include the AudioSet labels and 6 motion regressors the reports are generated, if I include one more `fmriprep` regressor, it runs a very long time without showing the reports.

**Comment by adelavega** [comment]
Do you know which one? It's possible that that that specific one is causing problems.

**Comment by adelavega** [comment]
Either way need to speed it up. Unfortunately the timing is store relative to the stimulus, not the run, so it basically has to add the stimulus onset to each onset for the predictor, for each subject x run...

**Comment by PeerHerholz** [comment]
I tested a few and the problems is the same no matter what, e.g. `csf` and `global signal` both cause the delay. I can also test a different dataset!?

**Comment by PeerHerholz** [comment]
Running into the same problem for Sherlock and Sherlock/Merlin.

**Comment by adelavega** [comment]
Cool thanks. Sounds like it's those regressors which makes sense as we
hadn't used them in our models. Will try to find out why
