### ISSUE TITLE
Non-editable analyses in DRAFT mode appear editable

### ISSUE THREAD

**Issue by adelavega** [neuroscout/neuroscout#759]
The frontend will let you seemingly edit an analysis in DRAFT that isn't yours, but then when you try to push to the server you (correctly) cannot save any changes.

**Comment by rwblair** [comment]
@adelavega  Ok looking into doing owner ship checks for builder or builder routes. Are the URLs to DRAFT showing up anywhere in the site for non owners? or do you have to enter the DRAFT URL directly to get there?

**Comment by adelavega** [comment]
you have to enter a draft URL directly to get there

**Comment by adelavega** [comment]
Let's also hold off rendering the analysis until we know if it should go into view only or editable mode, to prevent it looking like it can be edited and jumping into into view mode


Need to generalize view-only mode to also apply to viewing drafts that you don't own.
