### ISSUE TITLE
add option to scale/unscale report plots

### ISSUE THREAD

**Issue by adelavega** [neuroscout/neuroscout#762]
already available in the API

**Comment by rwblair** [comment]
scale by default

**Comment by adelavega** [comment]
Related: #760

**Comment by adelavega** [comment]
Note to self: only do unit scaling

**Comment by rwblair** [comment]
@adelavega We don't store a 'scale' boolean in the database right now. The dictionary the api returns for each plot has a config.scale.bandPaddingInner value, which is either 0.015 or 0.0 depending on type of plot. 

Then there's encoding.fill.scale, I tried curling against `api/analyses/AZ4qk/report?run_id=1233&scale=False` and `api/analyses/AZ4qk/report?run_id=1233` and the values didn't change. Am I passing the scale boolean properly there?

Is there a way for the front end to determine if a plot is scaled or not or will we need to start tracking that in the database?

**Comment by adelavega** [comment]
Closed with #788
