### ISSUE TITLE
mailgun procard expires in 30 days

### ISSUE THREAD

**Issue by adelavega** [neuroscout/neuroscout#771]
CC we're using for mailgun is going to expire, so we need to get the new procard whenever that is available @tyarkoni

**Comment by tyarkoni** [comment]
Right now only essential purchases are allowed with the ProCard, and I don't think this qualifies. Not sure what's going to happen yet. Will let you know when I know. But most likely we can ask the dept to cover this temporarily if need be.

**Comment by adelavega** [comment]
we're really only using the email to verify new users. we could only allow google SSO users to prevent needing any email, at least temporarily.

**Comment by adelavega** [comment]
good news. first 1250 emails are free, and we're not where near that limit, so as long as we have a CC # in the account, we should be good. very unlikely to get charged.

**Comment by adelavega** [comment]
added my personal cc
