### ISSUE TITLE
rename face id regressors

### ISSUE THREAD

**Issue by adelavega** [neuroscout/neuroscout#785]
currently they don't have face in the name, add that

**Comment by jsmentch** [comment]
Related question: I can't actually find them searching for id, f_id, id_ - what are they actually called now in the meantime so I can take a look at them?

**Comment by adelavega** [comment]
currently they are just `id_1` etc...

actually i'll just rename them now

**Comment by adelavega** [comment]
ah sorry, they are also private currently. i'll go ahead and make them public.

**Comment by adelavega** [comment]
okay done. they are now "face_id_{i]". thanks!
