### ISSUE TITLE
Face ID features question + face feature sampling rate

### ISSUE THREAD

**Issue by jsmentch** [neuroscout/neuroscout#818]
For a contrast I am trying to use, I need to get face id features at a finer time scale than 1Hz.

I've been playing around in pliers trying to extract this myself from the stimulus and wondering what was used to get face_id. GoogleVisionAPIFaceExtractor does not seem to give this output, was it MicrosoftAPIFaceExtractor or using a version of facenet outside of pliers? Would it be possible to be pointed to some code that did this that I could keep those same settings yet change the sample rate?

Here is the face_id predictor collection that I am trying to get at a finer time scale:
Collection: merlin_facenet_cw_min50_t62_top_faces | Face clustering identity for top 20 faces

A related general question is if 1Hz should be the default for features like face_id. I know there are tradeoffs, expenses, etc., but for me I will need a higher resolution even though the TR here was 1.5s. Even 2 Hz might be better as a default though I will try to get finer than that for this.

**Comment by adelavega** [comment]
Hey Jeff,
Unfortunately there's one major limitation w.r.t to all visual features, which is that the Frames for the video were sampled at 1hz. 

Therefore all visual features that follow from that are at 1hz. I think it's reasonable to want a higher sampling rate, we just arbitrarily decided on 1hz a long time ago (helps save space and keep things tidy). I'd consider going a little finer in future re-extractions (although that would be a significant effort).

Specifically about face_id, this feature is not in pliers, and I wrote a notebook to extract it. I used `face_net` to extract face encoding vectors and a clustering algorithm on those vectors to group faces in each stimulus into "identities". Not as automatic of a process as I'd like as it required choosing some parameters subjectively for each dataset (hence the t62, that is a threshold for the clustering algorithm that I decided on subjectively for each movie).

Here is the code: https://github.com/adelavega/face_priming

I think this is something that should be added to the documentation, so I will tag it with that

**Comment by adelavega** [comment]
You are welcome to try to replicate my code (in addition to sampling at a finer scale-- I just pulled the frames we had already sampled) and upload a new version of these stimuli.

**Comment by jsmentch** [comment]
Ahhh I see that makes sense. Okay, this should be a good start for me thanks for sharing the notebooks!

**Comment by adelavega** [comment]
Closing for now @jsmentch but feel free to comment here if you have any other issues or need me to do anything

**Comment by jsmentch** [comment]
@adelavega thanks! I've actually been stuck just trying to get facenet installed properly in a container. Any chance you have a container or a recipe available somewhere? Once I get it working, will probably have some questions.

**Comment by adelavega** [comment]
sure, i'm using conda, this is the environment I have. Hopefully this helps you, I think the trickiest thing is you want CUDA to work so if you have a GPU you can use it. 

```
name: tf_gpu_10
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _tflow_select=2.1.0=gpu
  - absl-py=0.7.1=py37_0
  - astor=0.7.1=py37_0
  - attrs=19.1.0=py37_1
  - backcall=0.1.0=py37_0
  - blas=1.0=mkl
  - bleach=3.1.0=py37_0
  - c-ares=1.15.0=h7b6447c_1
  - ca-certificates=2019.5.15=0
  - certifi=2019.6.16=py37_0
  - cloudpickle=1.2.1=py_0
  - cudatoolkit=10.1.168=0
  - cudnn=7.6.0=cuda10.1_0
  - cupti=10.1.168=0
  - cycler=0.10.0=py37_0
  - cytoolz=0.10.0=py37h7b6447c_0
  - dask-core=2.1.0=py_0
  - dbus=1.13.6=h746ee38_0
  - decorator=4.4.0=py37_1
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py37_0
  - expat=2.2.6=he6710b0_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.9.1=h8a8886c_1
  - gast=0.2.2=py37_0
  - glib=2.56.2=hd408876_0
  - gmp=6.1.2=h6c8ec71_1
  - google-pasta=0.1.7=py_0
  - grpcio=1.16.1=py37hf8bcb03_1
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - h5py=2.9.0=py37h7918eee_0
  - hdf5=1.10.4=hb1b8bf9_0
  - icu=58.2=h9c2bf20_1
  - imageio=2.5.0=py37_0
  - intel-openmp=2019.4=243
  - ipykernel=5.1.1=py37h39e3cac_0
  - ipython=7.6.1=py37h39e3cac_0
  - ipython_genutils=0.2.0=py37_0
  - ipywidgets=7.5.0=py_0
  - jedi=0.13.3=py37_0
  - jinja2=2.10.1=py37_0
  - joblib=0.13.2=py37_0
  - jpeg=9b=h024ee3a_2
  - jsonschema=3.0.1=py37_0
  - jupyter_client=5.3.1=py_0
  - jupyter_core=4.5.0=py_0
  - keras-applications=1.0.8=py_0
  - keras-preprocessing=1.1.0=py_1
  - kiwisolver=1.1.0=py37he6710b0_0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.8.0=hd408876_0
  - libsodium=1.0.16=h1bed415_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.0.10=h2733197_2
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.9=hea5a465_1
  - markdown=3.1.1=py37_0
  - markupsafe=1.1.1=py37h7b6447c_0
  - matplotlib=3.1.0=py37h5429711_0
  - mistune=0.8.4=py37h7b6447c_0
  - mkl=2019.4=243
  - mkl-service=2.0.2=py37h7b6447c_0
  - mkl_fft=1.0.12=py37ha843d7b_0
  - mkl_random=1.0.2=py37hd81dba3_0
  - nb_conda=2.2.1=py37_0
  - nb_conda_kernels=2.2.2=py37_0
  - nbconvert=5.5.0=py_0
  - nbformat=4.4.0=py37_0
  - ncurses=6.1=he6710b0_1
  - networkx=2.3=py_0
  - notebook=6.0.0=py37_0
  - numpy=1.16.4=py37h7e9f1db_0
  - numpy-base=1.16.4=py37hde5b4d6_0
  - olefile=0.46=py37_0
  - openssl=1.1.1c=h7b6447c_1
  - pandas=0.24.2=py37he6710b0_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py37_1
  - parso=0.5.0=py_0
  - patsy=0.5.1=py37_0
  - pcre=8.43=he6710b0_0
  - pexpect=4.7.0=py37_0
  - pickleshare=0.7.5=py37_0
  - pillow=6.1.0=py37h34e0f95_0
  - pip=19.1.1=py37_0
  - prometheus_client=0.7.1=py_0
  - prompt_toolkit=2.0.9=py37_0
  - protobuf=3.8.0=py37he6710b0_0
  - ptyprocess=0.6.0=py37_0
  - pygments=2.4.2=py_0
  - pyparsing=2.4.0=py_0
  - pyqt=5.9.2=py37h05f1152_2
  - pyrsistent=0.14.11=py37h7b6447c_0
  - python=3.7.3=h0371630_0
  - python-dateutil=2.8.0=py37_0
  - pytz=2019.1=py_0
  - pywavelets=1.0.3=py37hdd07704_1
  - pyzmq=18.0.0=py37he6710b0_0
  - qt=5.9.7=h5867ecd_1
  - readline=7.0=h7b6447c_5
  - scikit-image=0.15.0=py37he6710b0_0
  - scikit-learn=0.21.2=py37hd81dba3_0
  - scipy=1.3.0=py37h7c811a0_0
  - seaborn=0.9.0=py37_0
  - send2trash=1.5.0=py37_0
  - setuptools=41.0.1=py37_0
  - sip=4.19.8=py37hf484d3e_0
  - six=1.12.0=py37_0
  - sqlite=3.29.0=h7b6447c_0
  - statsmodels=0.10.0=py37hdd07704_0
  - tensorboard=1.14.0=py37hf484d3e_0
  - tensorflow=1.14.0=gpu_py37h74c33d7_0
  - tensorflow-base=1.14.0=gpu_py37he45bfe2_0
  - tensorflow-estimator=1.14.0=py_0
  - tensorflow-gpu=1.14.0=h0d30ee6_0
  - termcolor=1.1.0=py37_1
  - terminado=0.8.2=py37_0
  - testpath=0.4.2=py37_0
  - tk=8.6.8=hbc83047_0
  - toolz=0.10.0=py_0
  - tornado=6.0.3=py37h7b6447c_0
  - tqdm=4.32.1=py_0
  - traitlets=4.3.2=py37_0
  - wcwidth=0.1.7=py37_0
  - webencodings=0.5.1=py37_1
  - werkzeug=0.15.4=py_0
  - wheel=0.33.4=py37_0
  - widgetsnbextension=3.5.0=py37_0
  - wrapt=1.11.2=py37h7b6447c_0
  - xz=5.2.4=h14c3975_4
  - zeromq=4.3.1=he6710b0_3
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pip:
    - cffi==1.13.2
    - chardet==3.0.4
    - dask==2.1.0
    - facenet==1.0.4
    - idna==2.8
    - llvmlite==0.31.0
    - numba==0.48.0
    - opencv-python==4.1.0.25
    - pycparser==2.19
    - pydub==0.23.1
    - pyns==0.3.1
    - requests==2.22.0
    - resampy==0.2.2
    - soundfile==0.10.3.post1
    - urllib3==1.25.3
prefix: /home/alejandro/anaconda3/envs/tf_gpu_10
```

**Comment by adelavega** [comment]
you should be able to do:
`conda env create -f environment.yml`
where environment.yml is the contents of what I just pasted.

**Comment by adelavega** [comment]
also, remember that the scripts I have in that repo load already extracted frames (at 1hz) for each dataset, so you'll have to resample using pliers and start from there. 

i'm happy to chat sometime if you need more help once you try it out.

**Comment by jsmentch** [comment]
I was able to create (I think) a working singularity container from that conda config after some wrangling, thanks!

One maybe simple question that might save me some time is: is there a standard way to go from extracted frames to a .csv of all of the frames in the format that the notebooks ingest? I can extract the frames with pliers and see their info, but how do I save them all and get the .csv listing each of their paths?

**Comment by adelavega** [comment]
Great. 

No standard way, you'll have to do some wrangling with pandas / plliers to get that to happen. I did the same but from the database to the `.csv` file. Off the top of my head, I think you'll have to loop over the frame container, and save each frame, and make a pandas dataframe referencing the saved frames while looping.
