### ISSUE TITLE
allow unititled analyses?

### ISSUE THREAD

**Issue by adelavega** [neuroscout/neuroscout#823]
should we allow analyses to not have a name? 
names can always be given later, and i often find myself struggling with name when im just trying things out.

maybe we can allow users to create without a name, but a name must be given prior to compliation?

**Comment by tyarkoni** [comment]
I don't see a reason to allow names to be blank... users can always put something temporary and then edit later. If we were to require them for compilation, they'd have to go back and edit it anyway, so it doesn't feel like much of a blocker. But if you think it makes a difference and want to allow blanks, that's fine with me.

**Comment by adelavega** [comment]
yeah, it's not much of a blocker i just noticed almost every single person that tried out neuroscout for the first time goes "oh i need to put a name to go the next tab (and explore features). hmm what should I put, I guess i'll put a random name". 

so I think we should just allow no name, and if you don't have a name in he compilation page it makes you give one (on that page without going back we can have a field).
