### ISSUE TITLE
template latest version on frontend

### ISSUE THREAD

**Issue by adelavega** [neuroscout/neuroscout#826]
instead of `latest` the specific version tag.

maybe pull directly from github

**Comment by rwblair** [comment]
This was specifically for version of the docker image used in the command shown in the review tab.

**Comment by adelavega** [comment]
@rwblair looks like we can use the docker hub api to pull tags directly:

https://hub.docker.com/v2/repositories/neuroscout/neuroscout-cli/tags

if we took those results and sorted by date, and excluced "latest" we could get the most recent version of the neuroscout-cli docker image available. 
 
is this something that would be allright to handle directly in the frontend?

**Comment by rwblair** [comment]
Just ran curl on that endpoint, looks good. Can work with it, looks to me like its already coming back sorted by date so hopefully wont have to deal with pagination.

**Comment by adelavega** [comment]
closed by #837
