### ISSUE TITLE
change title of browser depending on builder status

### ISSUE THREAD

**Issue by adelavega** [neuroscout/neuroscout#845]
Currently it's always "Neuroscout" which is not very helpful when looking at your history.

Can we change this to reflect analysis name, or which page we're on?

**Comment by rwblair** [comment]
fortunately setting the title is pretty easy, but it is another piece of state to be tracked. commit I just pushed sets the analysis ID into the title if its in the url, being done in the routes page. But now that I think about it, setting title is probably a very cheap operation that could be done on every render of a component, where we could get at actual state or props info like analysis name.

**Comment by rwblair** [comment]
Well never mind my changes for setting in routes render. I'll try again inside actual component render.
