### ISSUE TITLE
Can't make an analysis private via web interface

### ISSUE THREAD

**Issue by jsmentch** [neuroscout/neuroscout#846]
<img width="741" alt="Screen Shot 2020-11-13 at 9 22 43 AM" src="https://user-images.githubusercontent.com/20958589/99082278-f4a6f480-2591-11eb-942d-28d87060aed8.png">

in case you aren't aware, front end bug:
Clicking on the "public" toggle will expand/hide "edit analysis details" instead of toggling between public/private, at least on a macbook, making it unable to set an analysis as private

**Comment by adelavega** [comment]
thanks! cc: @rwblair

**Comment by adelavega** [comment]
Fixed with #841
