### ISSUE TITLE
Show user-friendly fatal errors

### ISSUE THREAD

**Issue by skept** [neuroscout/neuroscout#92]

**Comment by adelavega** [comment]
I'm not 100% sure what this was about but I'm guessing it means that the debug notifications could be disabled, while still allowing error notifications.

**Comment by adelavega** [comment]
We should disable the debug notifications now

**Comment by adelavega** [comment]
@rwblair let's disable these

**Comment by adelavega** [comment]
This is mostly taken care of, but there are still a few instances where we could more graceful fail.

**Comment by adelavega** [comment]
Closing until we find specific instances of this issue
