### ISSUE TITLE
Allow user to edit existing transformation

### ISSUE THREAD

**Issue by skept** [neuroscout/neuroscout#96]
@tyarkoni Since it's not too much work for the user to just delete a transformation and add a new one I'm assuming the edit functionality is lower priority?

**Comment by tyarkoni** [comment]
Sounds reasonable, definitely not a high priority for now.

**Comment by tyarkoni** [comment]
Oh, but if editing is not possible, then we want to make sure the user can easily re-order transformations in the list, since the order in which they're applied can be pretty important.

**Comment by skept** [comment]
Good point, I can see how reordering is probably even more important than editing. I added a separate issue: #98

**Comment by adelavega** [comment]
Closed with #439
